### PR TITLE
Update hue logic

### PR DESCRIPTION
**Pull request by detonavomek-zz**
Adding new commands is more easier now.

### CODE REVIEW

**Comment by s0md3v** [comment]
Thanks.
This is just perfect.

**Comment by s0md3v** [comment]
Hi there!
Can you provide me your email or twitter?
I want to talk about something.

**Comment by detonavomek-zz** [comment]
@UltimateHackers, sure. You can write to me here: detonavomek@gmail.com

**Comment by detonavomek-zz** [comment]
@s0md3v just found this notification again. 
I thing that I miss mail from you :(

**Comment by s0md3v** [comment]
I am so sorry 😌 and now I have really forgotten what I wanted to talk about.

**Pull request merged**
