### PR TITLE
adding a fluent interface

### PR DESCRIPTION
**Pull request by emehrkay**
I know that you didn't ask for this, but I thought it would be a cool addition to the project. I updated the readme to show how it would work.

### CODE REVIEW

**Comment by s0md3v** [comment]
Thanks mate. But the idea was to make the API as simple as possible but you are just complicating it.

**Comment by emehrkay** [comment]
You think it complicates things?

```python
Hue('test').red.bg.bold
```

seems easier than

```python
red(bg(bold('test')))
```

But cool, I'll fork. Thanks for the project

**Comment by s0md3v** [comment]
According to me, it does.
But ts cool to modify it according to your needs as long as credits are given.
Thanks again.
Have a nice day.

**Comment by s0md3v** [comment]
And for proving my point
```
print red('Red text')
```
seems more minimal than
```
print Hue('Red text').red
```

**Comment by emehrkay** [comment]
Yeah you're definitely right when it comes to single calls. However, the `Hue` class is setup to so that its instances are callable so something like this is possible:

```python
H = Hue('')

# later in code
print H.red('red text')

#or 
print H.red('red text').bold
```

I guess the inspiration for the fluent interface are prototypes JavaScript. Since we cannot 'easily' prototype in Python, I figured an object that calls functions is the next best thing.

You can have JS do this

```javascript
'red text'.bold().red()

# by defining
String.prototype.bold = function(){
    return '<strong>' + this + '</strong>';
}

...and so on
```

Anyway, Hue is a cool project. don't let me complicate it lol

**Pull request closed without merging**
